device: "cpu"
output_dir: "data/high_res_results/"
save_vis: false
use_calibration: false
default_material_id: 0

if use_calibration:
  calibration_ref_path: "calibration_ref.jpg"

patching:
  use_patching: false
  patch_size: 640

models:
  spectrum_inv:
    weights: "weights/last_spectrum_inv.pth"

  detector:
    weights: "weights/uark_detector_v3.pt"
    conf_thresh: 0.2
    iou_thresh: 0.05

  classifier:
    weights: "weights/flake_monolayer_classifier.pth"
    class_names: ['1-layer', '5plus-layer']
    num_materials: 2
    material_dim: 64
    freeze_cnn: false